- cav_msgs/CMakeLists.txt
- cav_msgs/package.xml
- cav_srvs/CMakeLists.txt
- cav_srvs/package.xml
- j2735_msgs/CMakeLists.txt
- j2735_msgs/package.xml
Updated copyright notice on all source files to reflect 2019 (CAR-214)
> Copyright updated.

- cav_msgs/msg/ManeuverPlan.msg
- cav_srvs/srv/PlanManeuvers.srv
Minor updates to the maneuver planning messages in support of usdot-fhwa-stol/CARMAPlatform#390.
> Fix maneuver planning messages for minimal arbitrator

- cav_msgs/msg/DriverStatus.msg
added lidar_lite_v3hp for the status to be true when available
> added lidar_lite_v3hp

- cav_msgs/msg/ExternalObject.msg
- cav_msgs/msg/PredictedState.msg
- cav_msgs/msg/RoadwayObstacle.msg
Updated the "ExternalObject" and "RoadwayObstacle" messages and added the "PredictedState" message to represent the world model interface for external objects.
> updated messages to represent external objects

- can_msgs/package.xml
- cav_msgs/package.xml
- cav_srvs/package.xml
- j2735_msgs/package.xml
For testarossa release xml version changes
> updated versions to 1.1.0

- docs/pull_request_template.md
> adding PR template

- can_msgs/package.xml
- cav_msgs/package.xml
- cav_srvs/package.xml
- j2735_msgs/package.xml
Updated package.xml versions for new release. One .xml file was not versioned to our standard in 1.2.0, so now we are pushing this update.
> CARMAMsgs_1.2.1 component release

- cav_msgs/msg/DriverStatus.msg
- cav_msgs/msg/LightBarStatus.msg
Added new fields for following msgs to support lightbar driver:
-`cav_msgs/LightBarStatus` : Added new fields for new lightbar patterns
-`cav_msgs/DriverStatus` : Added new field `lightbar` driver for driver discovery
Accompanying lightbar driver code is in [this PR](https://github.com/usdot-fhwa-stol/CARMALightbarDriver/pull/1)
Related issue is in CARMA: [here](https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/573)
Lightbar is not controlled through software as of now. Therefore CARMA compatible ROS driver is needed to control it.
Details are in the above link.
> adjusted msgs to support lightbar

- cav_msgs/package.xml
Updated version for changed xml
part of 1.3.0 release
> updated xml version of cav_msgs for release 1.3.0

- cav_msgs/msg/RoadwayObstacleList.msg
This PR renames the old RoadwayEnvironment.msg to RoadwayObstacleList.msg to mirror the pattern used by ExternalObjectList and ExternalObject. 
Supports progress towards usdot-fhwa-stol/CARMAPlatform#432
Makes the carma objects interface clearer and more consistent. 
Local builds and searches to verify nothing is currently using this message. 
> Create roadway obstacle list message

- cav_msgs/msg/LightBarCDAType.msg
- cav_msgs/msg/LightBarIndicator.msg
- cav_msgs/msg/LightBarIndicatorControllers.msg
- cav_msgs/msg/LightBarStatus.msg
- cav_srvs/srv/ReleaseIndicatorControl.srv
- cav_srvs/srv/RequestIndicatorControl.srv
- cav_srvs/srv/SetLightBarIndicator.srv
- cav_srvs/srv/SetLights.srv
Added new messages to make lightbar manager work
https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/625
Added lightbar_manager to CARMAPlatform. These messages are required for its operation.
Unit tested and integration tested using mock_drivers.
> initial commit

- README.md
Updates necessary for skewer case repo name change
none
DoT request
> Updating for skewer case naming convention

- cav_msgs/msg/ControlBounds.msg
- cav_msgs/msg/ControlMessage.msg
- cav_msgs/msg/ControlRequest.msg
- cav_msgs/msg/DaySchedule.msg
- cav_msgs/msg/PathPart.msg
- cav_msgs/msg/Point.msg
- cav_msgs/msg/Schedule.msg
- cav_msgs/msg/ScheduleParams.msg
- j2735_msgs/msg/ControlBounds.msg
- j2735_msgs/msg/ControlMessage.msg
- j2735_msgs/msg/ControlRequest.msg
- j2735_msgs/msg/ControlType.msg
- j2735_msgs/msg/ControlValue.msg
- j2735_msgs/msg/DaySchedule.msg
- j2735_msgs/msg/PathPart.msg
- j2735_msgs/msg/Point.msg
- j2735_msgs/msg/Schedule.msg
- j2735_msgs/msg/ScheduleParams.msg
- j2735_msgs/msg/VType.msg
Added Geofence inital ROS msg definitions.
New msgs are in j2735_msgs as well as in cav_msgs where applicable.
https://github.com/usdot-fhwa-stol/carma-platform/issues/674
Addition of Geofence capability in CARMA requires these msgs
j2735_msgs and cav_msgs are buildable
> Add initial ROS Msg definition of Geofence 

- cav_srvs/srv/ComputePlanCost.srv
> Add ComputePlanCost.srv

- cav_msgs/msg/CarlaEnabled.msg
Add CarlaEnabled message for Carla Simulator status indication
> Add CarlaEnabled for Carla simulator status

- .circleci/config.yml
Reduce CI memory usage by limiting the number of jobs
Improve CI reliability
CI
> Reduce CI memory usage

- can_msgs/package.xml
- cav_msgs/package.xml
- cav_srvs/package.xml
- j2735_msgs/package.xml
PR for updating package.xml files.
Changed package.xml files for every package in this repository to format 3.
This change is required to move carma to newer software.
This has been tested by successfully building this repository.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)
> Updated package.xml files PR

- cav_msgs/msg/LaneChangeInfo.msg
A new message is created to communicate information about the lane change to the UI.
usdot-fhwa-stol/carma-platform#710
> add lane change info message

- cav_msgs/msg/TrajectoryPlanPoint.msg
This PR adds an orientation field to the carma trajectories. This will allow for better interoperability with autoware components as well as more detailed trajectory planning in future plugins. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/859
See description
> Add orientation to trajectory definition

- cav_msgs/msg/TrajectoryPlanPoint.msg
PR changes the time definition in the trajectory message to ros time absolute reference
Supports usdot-fhwa-stol/carma-platform#859
Clearer trajectory API and easier to debug logic
Testing in progress on integration/routing branch
> Change target_time data type

- .circleci/config.yml
This PR is to merge the changes from 3.4.3 release back into the develop branch. Also retargets CI back to develop
This is needed to keep the develop branch as a working version of our released master branch.
Has been tested as part of the Wanderer testing process.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)
> Feature/sync 3.4.3

- cav_msgs/CMakeLists.txt
- cav_msgs/package.xml
- cav_srvs/CMakeLists.txt
- cav_srvs/package.xml
- j2735_msgs/CMakeLists.txt
- j2735_msgs/package.xml
> updated copyright text

- cav_srvs/srv/SetTrafficEvent.srv
Add srv to support UI pass in parameters
https://github.com/usdot-fhwa-stol/carma-platform/issues/1095
Traffic Incident Use Case
Local Integration testing
> Traffic Incident Management :  CARMA -Messenger: Update Traffic Incident Publisher Node for Messenger UI

- cav_srvs/srv/PlanTrajectory.srv
> Add vehicle state stamp

- cav_srvs/srv/PlanTrajectory.srv
The TrajectoryPlan.srv is updated by adding an initial trajectory plan to its request section, so the service can work with Yield plugin.
Supports usdot-fhwa-stol/carma-platform#1089
https://github.com/usdot-fhwa-stol/carma-platform/issues/1089
To allow Yield plugin to communicate with other tactical plugins such as inlane cruising, and modify their trajectories for object avoidance.
Unit test and ros test
> update PlanTrajectory srv to work with Yield plugin

- cav_msgs/msg/TrafficEventInfo.msg
Traffic Event Information message specs. It is used for UI to display traffic incident related information on the side panel of UI.
N/A
Traffic Incident Use Case
N/A
N/A
> Traffic Incident Management: CARMA Web UI

- cav_msgs/msg/CheckActiveGeofence.msg
Update CheckActiveGeofence to include necessary information for UI display
N/A
N/A
N/A
N/A
> Update CheckActiveGeofence msg

- carma_debug_msgs/msg/LaneletIdRegulatoryElementPair.msg
- carma_debug_msgs/msg/MapUpdateReadable.msg
- carma_debug_msgs/msg/RegulatoryElement.msg
- cav_msgs/msg/Route.msg
Synchronize Zephyr release branch back into develop to address CARMA Platform CI build issue
> Sync develop with release branch

- cav_msgs/msg/TrafficControlRequestPolygon.msg
Supports TCR visualization on UI for more information and debug purposes.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1294
See above.
> TCR polygon support

- .circleci/config.yml
- cav_msgs/msg/TrafficControlRequestPolygon.msg
Merge zephyr changes back into develop to support further development while zephyr testing continues. 
See above
> Sync develop with zephyr

- cav_msgs/msg/PlatooningInfo.msg
Missing actual gap in platoon info msg
N/A
Testing platoon 
Vehicle
> Missing actual gap in platoon info msg

- cav_msgs/msg/UpcomingLaneChangeStatus.msg
> Commit changes to UpcomingLaneChangeStatus.msg

- .circleci/config.yml
This PR makes a small correction to the ci file in this repo to correctly point to noetic/develop images. 
> Update tags for noetic develop

- .circleci/config.yml
PR Updates the circle ci config file use for CI to use colcon for building and testing the packages in this repo
All build commands should use colcon instead of catkin in ros noetic. 
> Update config.yml to use colcon for the build and test commands

- cav_msgs/msg/MobilityHeader.msg
- cav_msgs/msg/MobilityOperation.msg
- cav_msgs/msg/PlatooningInfo.msg
Sync noetic/develop with the 3.7 release
> Feature/sync noetic with 3.7.0

- .circleci/config.yml
Updated config to point develop from 3.7.0
> Updated config to point develop from 3.7.0

- .circleci/config.yml
This PR updates CI for foxy/develop to build both the ROS1 and ROS2 messages. 
Functional mixed version CI
This PR
> Add CI support for ROS1 and ROS2

- cav_msgs/msg/LaneFollowingManeuver.msg
- cav_msgs/msg/ManeuverParameters.msg
- cav_srvs/srv/PlanManeuvers.srv
- cav_srvs/srv/SetActiveRoute.srv
Sync develop after the 3.8.0 release with noetic/develop
> Sync noetic with develop after the 3.8.0 release 

- can_msgs/CMakeLists.txt
- can_msgs/package.xml
This PR updates the can_msgs package to compile in both ROS1 and ROS2. This package had previously been ported to be ROS2 only, but I just realized that it is required for one of the ROS1 drivers and so needs to be backward compatible until the drivers are done being ported. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/milestone/4
ROS2 version of carma-platform
Tested in both ROS1 and ROS2
> Update the can_msgs package to compile in both ros1 and ros2

- can_msgs/CMakeLists.txt
This PR adds the required dependency to the can_msgs CMakeLists
> add std_msgs dep

- Dockerfile
This PR fixes a topic name in the carma-msgs docker image after the corresponding change was merged to develop in this PR https://github.com/usdot-fhwa-stol/autoware.ai/pull/201
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/1609
ros1_bridge is synched with develop
> Correct target branch in docker file build

- Dockerfile
Update version numbers for 4.0.3 hotfix release
> Update version number for 4.0.3 hotfix

- j2735_v2x_msgs/msg/Position3D.msg
This PR fixes range constants and data type for the Position3D message fields. 
> fix constants and data type

- carma_v2x_msgs/msg/TrafficControlDetail.msg
- cav_msgs/msg/TrafficControlDetail.msg
- j2735_msgs/msg/TrafficControlDetail.msg
- j2735_v2x_msgs/msg/TrafficControlDetail.msg
Update carma messenger encoder/decoder for TCM updates. Add max platoon size and min headway to:
- Update CAV/ros messages
- J2735 msg file
- J2735 converter
- These changes are in an [accompanying PR](https://github.com/usdot-fhwa-stol/carma-messenger/pull/139) in carma-messenger
- CARMA messenger encoder/decoder
- These changes are in an [accompanying PR](https://github.com/usdot-fhwa-stol/carma-messenger/pull/139) in carma-messenger
Acceptance Criteria:
CAV messages, J2735 msg file, J2735 converter updated, messenger encoder/decoder updated with max platoon size and min headway fields
Adding fields: https://github.com/usdot-fhwa-stol/carma-platform/issues/1756
Per https://usdot-carma.atlassian.net/browse/CAR-5344, these fields are needed. 
The j2735_convertor has unit tests for each …
> update tcm fields

- carma_v2x_msgs/msg/MobilityReason.msg
- carma_v2x_msgs/msg/MobilityRepeat.msg
- carma_v2x_msgs/msg/MobilityResponse.msg
- carma_v2x_msgs/msg/PlanType.msg
- cav_msgs/msg/MobilityHeader.msg
- cav_msgs/msg/MobilityOperation.msg
- cav_msgs/msg/MobilityReason.msg
- cav_msgs/msg/MobilityRepeat.msg
- cav_msgs/msg/MobilityResponse.msg
The last PR for cav_msgs and carma_v2x_msgs made them different, this fixes that issue. 
> Fixed differences between cav_msgs and carma_v2x_msgs

- carma_planning_msgs/CMakeLists.txt
- carma_planning_msgs/package.xml
- carma_planning_msgs/srv/SetActiveRoute.srv
- cav_msgs/msg/RouteState.msg
- cav_srvs/srv/GetAvailableRoutes.srv
- cav_srvs/srv/SetActiveRoute.srv
As part of carma-platform PR [](url), the Route node was ported to ROS2, which required all route-related messages and services on the ROS1 and ROS2 side to use a matching snake_case naming convention in order to utilize the ros1_bridge. This PR includes the updates to those field names within the applicable route-related ROS1 messages.
Additionally, this PR includes an update to carma_planning_msgs/srv/SetActiveRoute.srv in order for its definition to match the defintion of the ROS1 cav_srvs/SetActiveRoute.srv
Related carma-platform PR: [Click Here](https://github.com/usdot-fhwa-stol/carma-platform/pull/1810)
Related carma-web-ui PR: [Click Here](https://github.com/usdot-fhwa-stol/carma-web-ui/pull/142)
[Issue #1809](https://github.com/usdot-fhwa-stol/carma-platform/issues/1809)
Built …
> Update field names for route-related messages and services

- .circleci/config.yml
- Dockerfile
- docker/checkout.bash
This PR is to merge release cabin changes into develop
> Sync dev with 4.2

- .circleci/config.yml
- .github/workflows/dockerhub.yml
- Dockerfile
This PR is to merge release branch into master for Xil release 4.4.3
> merge Release/k900 xil into master

- docker/install.sh
Fixes install.sh behavior where it was disregarding errors and reporting success
> install.sh: exit on error

- .github/workflows/docker.yml
- carma_v2x_msgs/CMakeLists.txt
- carma_v2x_msgs/msg/DetectedObjectCommonData.msg
- carma_v2x_msgs/package.xml
- docker/install.sh
- j3224_v2x_msgs/msg/ObjectType.msg
This PR fixes a build error in the carma_v2x_msgs package that was originally introduced by PR #208. 
Additionally, this PR includes an update for the Docker Push GitHub Action to fix an issue where the automated Docker Build was failing due to memory exhaustion.
Supports [CARMA Platform Issue #2123](https://github.com/usdot-fhwa-stol/carma-platform/issues/2123)
CDAR-175
This fixes a build issue that is keeping carma-msgs from building successfully.
Built locally; however PR should verify that the automated Docker build reported by GitHub is successful as well.
> Fix build error in carma_v2x_msgs

- docker/checkout.bash
This is a change we missed in the release candidate merge
@MishkaMN
> Add ros bridge to clone command

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- Dockerfile
- docker/checkout.bash
PR to update our checkout, build and CI processes to not be coupled to a specific branch. This PR uses a new action defined in the PR (https://github.com/usdot-fhwa-stol/actions/pull/34) which determines a Docker Hub organization and tag based on the GitHub event that triggers the action. Using this we are able to dynamically assign a base image for CI steps and for Dockerfile builds. Using other GitHub event data we are able to checkout current dependencies.
**This is a blocker to merging the master branch back into develop**
Reduce tedious work for release
CI
> Fix CI/Build to remove branch coupling

- .github/workflows/docker.yml
- docker/checkout.bash
- docker/install.sh
This PR updates `checkout.bash` to change the target directory in which the `ros1_bridge` repo is cloned into when the `BRANCH` environment variable is set to `develop`. Prior to this change, when `BRANCH` was set to `develop`, the `ros1_bridge` repo was cloned into /home/carma/src, but the `install.sh` script only builds ROS 2 packages located at ~/.base-image/ros2_msgs_ws
NA
CAR-6031
See above
Local integration test
CI (docker/docker action)
> Fix target directory for cloned ros1_bridge repository to ensure it is built in final image

- Dockerfile
- docker/checkout.bash
- docker/install.sh
This PR updates the Docker file, install.sh and checkout.bash scripts for the CARMA msgs repository to handle `GIT_BRANCH` argument.
-  Updated Docker file to pass GIT_BRANCH argument and added Metadata arguments to get metadata during docker builds. 
- Building checkout.bash from Docker file instead of install.sh script. 
- Updated checkout.bash to ignore the -d flag if mistakenly passed from other scripts, preventing execution errors by conflicting with -b when building with build-image.sh.
https://usdot-carma.atlassian.net/browse/ARC-81
Tested in local by building with build-image.sh
> update scripts to pass arguments and build with build-image.sh

- .github/workflows/ci.yml
This PR updates the runner size to 16 cores in our current CI workflow to reduce reruns by the development team when builds or tests fail, which consumes more resource minutes.
> Update GitHub Actions Runner size

- .github/workflows/README.md
- .github/workflows/dockerhub.yml
> Add manual dockerhub trigger

- Dockerfile
- docker/checkout.bash
- entrypoint.sh
- init-env.sh
During the testing humble basic route following test, pacifica (which uses ROS1 controller; therefore, ROS1_bridge) was not engaging. It had and error  
```
[RTPS_READER_HISTORY Error] Change payload size of '24' bytes is larger than the history payload size of '11' bytes and cannot be resized. -> Function can_change_be_added_nts
```
Someone else had the same problem and determined it was due to fastrtps (link included). 
carma live vehicles actually use cyclone, which I forgot to include in the docker images creation for carma-msgs since it stopped used carma-base as its base. 
So I used cyclone was RMW and the service is working fine.
https://github.com/eProsima/Fast-DDS/issues/213
ARC-285
ROS2 Humble Basic Route Following integration testing between ROS2 and ROS1 containers using this …
> use cyclone by default

- Dockerfile
- docker/build-image.sh
Duplicate of https://github.com/usdot-fhwa-stol/carma-base/pull/245
Due to recent update to the ROS signing key, the docker builds are failing. Please see https://discourse.ros.org/t/ros-signing-key-migration-guide/43937. However this would apply to existing installation of ROS (such as vehicles - so their guide should be updated)
Since docker image is created from scratch, we should follow the new ROS/ROS2 installation guide: https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debs.html
This is the PR that updates according to that. For this image specifically, not much change is required except the source list name changed in the new ros base image.
NA
NA
ROS Key update
Locally buildable
> Fix ROS Key

- .github/workflows/ci.yml
- .github/workflows/docker.yml
For this PR, first `fix-stingray-conflicts` was branched off of `release/stingray`, and then `master` was merged into `fix-stingray-conflicts` and merge conflicts were resolved. This was done to avoid fixing merge conflicts on PR #265.
The approach was based off of an approach described within [https://medium.com/@jshvarts/dealing-with-conflicts-when-merging-release-to-develop-da289a572f0d](https://medium.com/@jshvarts/dealing-with-conflicts-when-merging-release-to-develop-da289a572f0d )
[ARC-407](https://usdot-carma.atlassian.net/browse/ARC-407)
By fixing merge conflicts (from release/stingray -> master) with this branch, there will be no merge conflicts when merging release/stingray into master on RP #265 
Only non-functional changes are included, CI checks are used for testing. …
> Fix stingray conflicts
