usdot-fhwa-stol/carma-msgs

cav_msgs/CMakeLists.txt
cav_msgs/package.xml

Sometimes the build order will cause cav_msgs to build before j2735_msgs because the dependency was not properly linked. This PR resolves this in the Package.xml and CMakeLists.txt files of cav_msgs. The messages now build correctly. 
This should resolve issue #9

Fix cav_msgs cmakelists and package xml for j2735 deps

---

cav_msgs/CMakeLists.txt
cav_msgs/package.xml
cav_srvs/CMakeLists.txt
cav_srvs/package.xml
j2735_msgs/CMakeLists.txt
j2735_msgs/package.xml

PR to update copyright versions in dev. Unable to test via docker build because this repo does not have an associated Dockerfile / image. However, if you look at the diff below it's pretty clear that all that was changed was the copyright text at the top.

updated (C) version

---

cav_msgs/msg/TrailerAngle.msg

Trailer Angle custom message addition for header inclusion.
The trailer angle reported by the CARMAGarminLidarLiteV3DriverWrapper is published as an std_msgs/Float64 message type. It is difficult to use this message type reliably as it does not contain a timestamp which can be used for transform lookups. It should be updated to use a message type containing a header.
- [ x] New feature (non-breaking change that adds functionality)
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.

TrailerAngleMsg

---

cav_msgs/msg/RouteState.msg

This PR adds a current speed limit field to the RouteState message which can be used by the UI for display. 
Supports https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/592
Ensure UI has also information it needs for user display
Build completes

Add speed_limit field to route_state message

---

cav_msgs/msg/TrajectoryPlan.msg

This PR adds an initial velocity field to the trajectory plan message. Without this field it is not possible to properly convert times back to speeds as the speed at the first point is not known. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/pull/947
See referenced PR

Add initial velocity to trajectory plan

---

cav_srvs/srv/PlanTrajectory.srv

This PR adds a header to PlanTrajectoy who's stamp matches the vehicle_state field such that the planned trajectory can be properly timed. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/pull/1088
See issue in refered PR
1 run in blue lexus

Add vehicle state stamp

---

cav_srvs/srv/PlanTrajectory.srv

This PR adds a field to the PlanTrajectory.srv request in order to communicate to a tactical plugin which maneuver plan index the request is for.
Related PR in carma-platform: [Refactor plan_delegator and tactical plugins for plan_trajectory_cb() maneuver sequencing](https://github.com/usdot-fhwa-stol/carma-platform/pull/1220)
[Issue 1106: Refactor plan_delegator and InLane-cruising to properly sequence maneuver/trajectory planning](https://github.com/usdot-fhwa-stol/carma-platform/issues/1106)
[Isseu 1036: Inlane cruising plugin cannot create trajectory plan for distributed maneuvers](https://github.com/usdot-fhwa-stol/carma-platform/issues/1036)
Prior to this update, a tactical plugin in carma-platform would loop through a received maneuver plan and plan a trajectory for all relevant …

Update PlanTrajectory.srv request to communicate maneuver index to be planned

---

carma_debug_msgs/CMakeLists.txt
cav_msgs/CMakeLists.txt
cav_srvs/CMakeLists.txt
j2735_msgs/CMakeLists.txt

Update the CMakeLists.txt files to specify c++14 instead of C++11. 
Using C++ 14 to compile the CARMA source code on Ubuntu 20.04.
Full build and checking the output logs for C++ 14 usage.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)

Update ROS Noetic branch to C++14

---

cav_msgs/msg/UpcomingLaneChangeStatus.msg

As identified in CAR-2785: Create High Level Design for Basic TravelDONE, UI needs a simple topic to display what is the next lane change direction is (left/right) and how far it is until an upcoming lane change is required. This story is to develop this logic, which should leverage existing plugins to identify when the lane change will actually occur and to make this information available to the UI. It is understood that the lane change location cannot be known sooner than it is planned by the relevant plugin. Should be published as soon as it is known and updated as actual point of lane change approaches or shifts.

Commit enumeration change to UpcomingLaneChange.msg

---

j2735_msgs/msg/LaneAttributesTrackedVehicle.msg

Fixes issue where the quotation marks in `LaneAttributesTrackedVehicle.msg` were UTF-8 characters. The UTF-8 characters resulted in reading issues on systems with a non-UTF-8 locale. The UTF-8 quotes have been replaced with ASCII quotes, which resolved the issue.
Closes usdot-fhwa-stol/carma-msgs#112
The comment block in the `LaneAttributesTrackedVehicle.msg` file erroneously used UTF-8 quotation markings instead of ASCII quotes. This caused problems when a system (Docker container) using the POSIX locale tried to read the file. When the file was opened to generate the corresponding ROS message implementation, the build would crash because the quote marks could not be decoded.
`j2735_msgs` package was built on a system using the `en_US.UTF-8` locale and a system using the `POSIX` locale. …

112 - Replace UTF-8 quotes with ASCII quotes

---

cav_msgs/msg/ManeuverParameters.msg

There is a typo in both carma-platform and carma-msgs where the ManeuverParameters.msg value "negotiation_type" is incorrectly spelled as "neogition_type" in multiple files
https://github.com/usdot-fhwa-stol/carma-platform/issues/1371
This change is to ensure that msg file values are correctly listed to avoid confusion.

Fix typo in ManeuverParameters.msg

---

cav_msgs/msg/LaneFollowingManeuver.msg

This PR updates the lane_following maneuver lane ids to not be a single value as a lane following maneuver can cross multiple lanelets this has been changed to an array. 
This PR is required by https://github.com/usdot-fhwa-stol/carma-platform/pull/1353
See linked PR
Message spec reflects implementation
Stop and wait testing used this branch

Update lane following lane ids to not be single lane

---

cav_srvs/srv/PlanManeuvers.srv

This PR updates the plan_maneuvers service call request to include the initial vehicle state at the start of planning. This state should be used by Strategic Plugins when the prior_plan is empty. The reasoning for this change is that currently all the Strategic Plugins contain duplicated code to get the current position/lane/velocity information in order to begin maneuver planning. This means its possible for two strategic plugins to returns plans starting from slightly offset locations based on call order. This will make sequencing plans difficult. This change should help resolve that by providing a fixed source of truth as well as reducing code duplication. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1377
See description
Build

Add vehicle state in plan_maneuvers service call request

---

cav_srvs/srv/SetActiveRoute.srv

This PR adds a 'choice' enumeration field to the SetActiveRoute service request, which indicates whether a RouteID (the name of a route file) or an array of destination points (specifically, an array of cav_msgs/Position3D points) is being provided. Additionally, a field for an array of cav_msgs/Position3D points is included in order to store the destination points, where the last point is the final destination point. This update is being added in order to enable the Port Drayage Plugin package in carma-platform to set a new active route based on a received destination point from CARMA Streets.
Related PRs:
carma-platform: PR #[1321](https://github.com/usdot-fhwa-stol/carma-platform/pull/1321)
carma-web-ui: PR #[92](https://github.com/usdot-fhwa-stol/carma-web-ui/pull/92)
Unit Tested in …

Update SetActiveRoute.srv to include a 'choice' field and a destination points array field

---

.circleci/config.yml
cav_msgs/msg/LaneFollowingManeuver.msg
cav_msgs/msg/ManeuverParameters.msg
cav_msgs/msg/MobilityHeader.msg
cav_msgs/msg/MobilityOperation.msg
cav_msgs/msg/PlatooningInfo.msg
cav_srvs/srv/PlanManeuvers.srv
cav_srvs/srv/SetActiveRoute.srv

Merge release/a1 branch to master for 3.8.0

Merge release/a1 branch to master for 3.8.0

---

.circleci/config.yml
can_msgs/package.xml
carma_debug_msgs/CMakeLists.txt
cav_msgs/CMakeLists.txt
cav_srvs/CMakeLists.txt
j2735_msgs/CMakeLists.txt

Sync develop with release/elise

Sync develop with elise

---

cav_srvs/srv/PluginActivation.srv

Add the plugin activation message back into cav_srvs after is was accidently removed in the ROS2 conversion.
Supports ROS2 milestone https://github.com/usdot-fhwa-stol/carma-platform/milestone/4
Allow ROS1 plugins to still build
Docker build testing

Add the plugin activation message back into cav_srvs

---

Dockerfile

This PR updates the permissions of the installation folder used for the ros1_bridge so that is can be sourced properly from a carma-config docker-compose file. 
Supports the ROS2 milestone https://github.com/usdot-fhwa-stol/carma-platform/milestone/4
ros1_bridge should be usable in a carma-config docker setup
Local testing using the development config

Fix install folder permissions for ros1_bridge

---

cav_msgs/CMakeLists.txt
cav_msgs/msg/MobilityHeader.msg
cav_msgs/msg/MobilityRequest.msg
cav_msgs/msg/MobilityResponse.msg
cav_msgs/msg/PlanType.msg
cav_msgs/msg/PlatooningInfo.msg

Update cav_msgs package to match ihp platooning strategic plugin.
No related issue.
The changes are made to support the ihp2 platooning strategic plugin. The following messages are changed:
- Mobility Header
- Mobility Request
- Mobility Response
- Plan Type
- Platooning Info
The updated CAV messages are compiled with ihp2 platooning strategic plugin.

Updated CAV message packages that can compile with same-lane join IHP strategic plugin.

---

carma_msgs/CMakeLists.txt
carma_msgs/package.xml
carma_msgs/rule.yml

Add missing rule.yml file for ros1_bridge to carma_msgs, so that /system_alert topic can be bridged
Supports: https://github.com/usdot-fhwa-stol/carma-platform/issues/1557
Functional Hybrid ROS1 and ROS2 system
local build testing and run testing

Add rule file for carma_msgs package ros1_bridge

---

cav_msgs/msg/SystemAlert.msg

This PR updates the ROS1 version of the SystemAlert message to include the source_node field used in ROS2. This will allow the health_monitor to distinguish between ros1 and ros2 nodes. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/1661
See issue
Black pacifica

Add source_node to cav_msgs/SystemAlert

---

carma_v2x_msgs/msg/TrafficControlMessage.msg
carma_v2x_msgs/msg/TrafficControlRequest.msg
cav_msgs/msg/ByteArray.msg
cav_msgs/msg/TrafficControlMessage.msg
cav_msgs/msg/TrafficControlRequest.msg

This PR updates ROS1 fieldnames to match their corresponding ROS2 fieldnames for the following ROS1 messages: TrafficControlRequest, TrafficControlMessage, ByteArray. Prior to this change, the ros1_bridge was unable to create a 2to1 bridge for the topics involving these messages.
Tested on Ford Fusion

Match ros1 message fieldnames to ros2 message fieldnames

---

carma_v2x_msgs/msg/MobilityPlanType.msg
carma_v2x_msgs/msg/MobilityReason.msg
carma_v2x_msgs/msg/MobilityRepeat.msg
carma_v2x_msgs/msg/MobilityResponse.msg
cav_msgs/msg/MobilityPlanType.msg
cav_msgs/msg/MobilityReason.msg
cav_msgs/msg/MobilityRepeat.msg
cav_msgs/msg/MobilityResponse.msg

The mobility message in carma_v2x_msgs and cav_msgs is missing three fields: plantype, reason, and repeatability. These messages should be created, added to the carma-messenger mobility message encoder/decoder, and unit tested. Related to [CAR-5343](https://usdot-carma.atlassian.net/browse/CAR-5343)
https://github.com/usdot-fhwa-stol/carma-platform/issues/1769
The unit tests in cpp_message for the mobility message response have been updated to use these three fields. 
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)

Update carma messenger encoder/decoder for mobility response additions

---

carma_planning_msgs/msg/PlatooningInfo.msg
cav_msgs/msg/PlatooningInfo.msg

PlatooningInfo message definition is expanded to include information on the preceding vehicle in the platoon. These changes are required for IHP2 gap regulation during a cut-in merge, which involves middle vehicles in a platoon opening an extra-large gap for a new vehicle to join the platoon through a lane change/merge

expand platoon info definition

---

carma_planning_msgs/msg/PlatooningInfo.msg
cav_msgs/msg/PlatooningInfo.msg

Changes the field names in PlatoonInfo.msg to be ROS2 compliant. The recent update to this message introduced camelCase fields which are not allowed in ROS2 and cause compilation errors when building this package. The fields have been renamed to snake_case for both the ROS1 and ROS2 messages to ensure bridge-compatibility.
This will likely require updates to whatever code was referencing these fields in CARMA Platform.
This enables compilation of all packages dependent on the ROS2 CARMA messages.

Change camelCase message fields to snake_case for ROS2 compatibility.

---

carma_v2x_msgs/msg/EmergencyVehicleResponse.msg
cav_msgs/msg/EmergencyVehicleResponse.msg

Added the EmergencyVehicleResponse message to cav_msgs and carma_v2x_msgs, paralleling the MobilityOperation message. 
https://usdot-carma.atlassian.net/browse/CF-414, and https://github.com/usdot-fhwa-stol/carma-platform/issues/1964
Ran all existing cpp_message unit tests, and they all passed. No way to actually test the message itself as of yet. 

added EVR message

---

carma_v2x_msgs/msg/ObstacleDetection.msg
carma_v2x_msgs/msg/VehicleData.msg
carma_v2x_msgs/msg/VehicleMass.msg
cav_msgs/msg/ObstacleDetection.msg
cav_msgs/msg/VehicleData.msg
cav_msgs/msg/VehicleMass.msg
j2735_msgs/msg/AmbientAirPressure.msg
j2735_msgs/msg/BumperHeight.msg
j2735_msgs/msg/CoefficientOfFriction.msg
j2735_msgs/msg/DisabledVehicle.msg
j2735_msgs/msg/EventDescription.msg
j2735_msgs/msg/NodeXY24b.msg
j2735_msgs/msg/ObstacleDetection.msg
j2735_msgs/msg/Priority.msg
j2735_msgs/msg/VehicleClassification.msg
j2735_msgs/msg/VehicleType.msg
j2735_v2x_msgs/msg/AmbientAirPressure.msg
j2735_v2x_msgs/msg/BumperHeight.msg
j2735_v2x_msgs/msg/CoefficientOfFriction.msg
j2735_v2x_msgs/msg/DisabledVehicle.msg
j2735_v2x_msgs/msg/EventDescription.msg
j2735_v2x_msgs/msg/NodeXY24b.msg
j2735_v2x_msgs/msg/ObstacleDetection.msg
j2735_v2x_msgs/msg/Priority.msg
j2735_v2x_msgs/msg/VehicleClassification.msg
j2735_v2x_msgs/msg/VehicleType.msg

This PR contains minor fixes to nested BSM Part II Content messages based on findings during CARMA Messenger PR #168 [Click Here](https://github.com/usdot-fhwa-stol/carma-messenger/pull/168)
These changes enable improved maximum/minimum value checks within j2735_convertor and also fix incorrect message field types for several messages.
Unit tested as part of related CARMA Messenger PR (linked above) and full carma-msgs image builds with these changes.

Fixes for nested BSM Part II messages

---

carma_v2x_msgs/msg/SensorDataSharingMessage.msg
cav_msgs/msg/SensorDataSharingMessage.msg
j3224_msgs/msg/SensorDataSharingMessage.msg
j3224_v2x_msgs/msg/SensorDataSharingMessage.msg

Previous message definitions of SensorDataSharingMessage.msg in cav_msgs, j3224_msgs, carma_v2x_msgs, and j3224_v2x_msgs had defined the value "HAS_REF_POS_XY_CONF" as an entry in the presence vector to access a valid ElevationConfidence message. This was updated to the value of "HAS_REF_POS_EL_CONF" to reflect the elevation namespace given the SAE J3224 specification.
Supports [CARMA Messenger Issue #205](https://github.com/usdot-fhwa-stol/carma-messenger/issues/205)
CDAR-130
Update to comply to SAE J3224 standard for SDSM
carma-msgs builds successfully and the updated values work in the SDSM convertor

Fix ElevationConfidence constant in SDSM msgs

---

carma_cooperative_perception_interfaces/CMakeLists.txt
carma_cooperative_perception_interfaces/package.xml
carma_cooperative_perception_interfaces/rule.yml

This PR adds ROS 1 bridge topic mapping rules for the `carma_cooperative_perception_interfaces` package. The package name does not adhere to the ROS 1 message naming conventions, so we need to manually specify the mapping.
Closes #222 
Closes [CDAR-548](https://usdot-carma.atlassian.net/browse/CDAR-548)
We need this mapping to bridge topics using these message between ROS 1 and ROS 2.
Manually tests
[CDAR-548]: https://usdot-carma.atlassian.net/browse/CDAR-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ROS 1 bridge mapping rules

---

carma_cooperative_perception_interfaces/msg/Detection.msg
carma_cooperative_perception_interfaces/msg/Track.msg

This PR adds `semantic_class` fields for `Detection.msg` and `Track.msg` messages. The fields are used by upstream and downstream components.
Closes #224 
Closes [CDAR-629](https://usdot-carma.atlassian.net/browse/CDAR-629)
See above.
Manually in integration tests.
[CDAR-629]: https://usdot-carma.atlassian.net/browse/CDAR-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add semantic class fields for track and detection

---

j2735_v2x_msgs/.clang-format
j2735_v2x_msgs/CMakeLists.txt
j2735_v2x_msgs/cmake/ament_auto_add_gtest.cmake
j2735_v2x_msgs/cmake/ament_auto_find_test_dependencies.cmake
j2735_v2x_msgs/include/j2735_v2x_msgs/to_floating_point.hpp
j2735_v2x_msgs/package.xml
j2735_v2x_msgs/test/test_to_floating_point.cpp

This PR adds some convenience functions to convert the SAE confidence enumerated values to floating point equivalents. The enumerated values aren't really useful beyond standardizing data representation in messages.
Closes [CDAR-734](https://usdot-carma.atlassian.net/browse/CDAR-734)
Need the confidence values to generate covariance matrices. Floating point representations help with this.
Unit tests.
[CDAR-734]: https://usdot-carma.atlassian.net/browse/CDAR-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add confidence enumerated values to floating points

---

j2735_v2x_msgs/include/j2735_v2x_msgs/to_floating_point.hpp

This PR refactors the static member access used in the `to_floating_point()` functions. The previous way of accessing resulted in compilation errors when using different compilers and compiler versions.
Closes [CF-809](https://usdot-carma.atlassian.net/browse/CF-809)
Resolves compiler errors when building with ROS Humble
Built and unit tested in Foxy and Humble.
[CF-809]: https://usdot-carma.atlassian.net/browse/CF-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor static member variable access to resolve compiler 

---

j2735_v2x_msgs/CMakeLists.txt
j3224_v2x_msgs/CMakeLists.txt

This PR fixes the installation of the include directory for the j2735 and j3224 v2x message packages.
NA
[ARC-258](https://usdot-carma.atlassian.net/browse/ARC-258)
This PR is needed for packages that include the file `j2735_v2x_msgs/to_floating_point.hpp` to build.
Confirmed that packages that need the file  `j2735_v2x_msgs/to_floating_point.hpp` can build.
[ARC-258]: https://usdot-carma.atlassian.net/browse/ARC-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ARC 258 Fix Include Install
